[package]
name = "boids_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.15.1", features = ["bevy_dev_tools"] }
bevy_math = "0.15.1"
fastrand = "2.0.2"
